### ISSUE TITLE
Long text

### ISSUE THREAD

**Issue by ckakumanu** [quassum/SwiftUI-Tooltip#25]
**Describe the bug**
Having a long text for the tooltip causes it to overshoot the bounds.

**To Reproduce**
`struct ContentView: View {
    var body: some View {
        Text("Hello")
            .tooltip(.bottom) {
                Text("The transaction fee covers PayPal processing costs and includes PayPal Buyer Protection")
            }
    }
}`

**Expected behavior**
It should stay within bounds and stretch vertically

**Screenshots**
<img width="1541" alt="Screen Shot 2022-08-23 at 11 01 53 am" src="https://user-images.githubusercontent.com/52488918/186045552-ba6ca0a6-af9a-4d5c-97c5-63a899342d41.png">

**Desktop (please complete the following information):**
 - OS: [e.g. iOS 15.5]

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone 13 Pro Max]

**Additional context**

**Comment by bring-shrubbery** [comment]
I've fixed this in #26 by adding `.width` and `.height` properties to the config. You can set those and the text will wrap. The downside is that it's always pre-set, so it won't scale down if there's not enough text inside.

**Comment by gerchicov-vg** [comment]
@bring-shrubbery it doesn't resolve the problem because view may be a small button which is located somewhere near the right screen edge and you can't just set frame size
